baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SUGAM'
theme='sans'

[pagination]
  disableAliases = false
  pagerSize = 4
  path = 'page'

[taxonomies]
  tag = "tags"
  category="categories"
  author = "authors"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2