# Congo theme for Hugo

name = "sans"
license = "MIT"
licenselink = "https://github.com/psugam/sans/blob/master/LICENSE"
description = "A minimal theme for Hugo."

homepage = "https://github.com/psugam/sans/"
demosite = "https://psugam.github.io/sans/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax highlighting", "dark mode"]
min_version="0.146.0"

[author]
  name = "Sugam Pokharel"
  homepage = "https://sugam-pokharel.com.np/"
